// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_AdonisMercado.DAL;

#nullable disable

namespace P1_AP1_AdonisMercado.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251009141723_ChangesToProperty")]
    partial class ChangesToProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_AdonisMercado.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_AP1_AdonisMercado.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("TipoId");

                    b.ToTable("EntradasHuacalesDetalles");
                });

            modelBuilder.Entity("P1_AP1_AdonisMercado.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Huacal Verde Tamaño Pequeña",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Huacal Verde Tamaño Mediana",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Huacal Verde Tamaño Jumbo",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 4,
                            Descripcion = "Huacal Rojo Tamaño Pequeña",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 5,
                            Descripcion = "Huacalo Rojo Tamaño Mediana",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 6,
                            Descripcion = "Huacal Rojo Tamaño Jumbo",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("P1_AP1_AdonisMercado.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_AP1_AdonisMercado.Models.EntradasHuacales", "EntradaHuacal")
                        .WithMany("DetalleHuacales")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_AP1_AdonisMercado.Models.TiposHuacales", "TipoHuacal")
                        .WithMany("EntradasHuacalesDetalle")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");

                    b.Navigation("TipoHuacal");
                });

            modelBuilder.Entity("P1_AP1_AdonisMercado.Models.EntradasHuacales", b =>
                {
                    b.Navigation("DetalleHuacales");
                });

            modelBuilder.Entity("P1_AP1_AdonisMercado.Models.TiposHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
